import { UserRole } from '../types';

export const BRAND_COLOR = '#08428C';

export const APP_CONFIG = {
  name: 'EduSync',
  tagline: 'Enterprise School Management & AI Analytics Platform',
  primaryColor: '#08428C',
  version: '2.4.0-PROD',
  supportEmail: 'enterprise@edusync.io',
  phone: '+1 (800) 555-EDU1',
};

export const ALL_ROLES: UserRole[] = [
  'Super Admin',
  'School Admin',
  'Principal',
  'Deputy Principal',
  'Bursar',
  'Teacher',
  'Class Teacher',
  'Librarian',
  'Nurse',
  'Parent',
  'Student',
  'Receptionist',
  'Transport Manager',
  'HR',
  'Store Manager',
  'Board Member',
];

export const INITIAL_STUDENTS = [
  {
    id: 'std-001',
    admission_number: 'ADM-2026-001',
    first_name: 'Sophia',
    last_name: 'Vance',
    gender: 'Female' as const,
    date_of_birth: '2012-05-14',
    class_id: 'cls-101',
    class_name: 'Grade 10 - Alpha',
    stream: 'Science & STEM',
    status: 'Active' as const,
    guardian_name: 'Marcus Vance',
    guardian_phone: '+1 (555) 234-5678',
    guardian_email: 'marcus.vance@gmail.com',
    address: '442 Maple Drive, Beverly Hills, CA',
    medical_conditions: 'Mild Asthma (Inhaler in Nurse Office)',
    blood_group: 'O+',
    allergies: 'Peanuts',
    enrolled_date: '2023-09-01',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    fee_balance: 0,
  },
  {
    id: 'std-002',
    admission_number: 'ADM-2026-002',
    first_name: 'Liam',
    last_name: 'Chen',
    gender: 'Male' as const,
    date_of_birth: '2011-11-03',
    class_id: 'cls-101',
    class_name: 'Grade 10 - Alpha',
    stream: 'Science & STEM',
    status: 'Active' as const,
    guardian_name: 'Elena Chen',
    guardian_phone: '+1 (555) 876-5432',
    guardian_email: 'elena.c@outlook.com',
    address: '1092 Silicon Blvd, San Jose, CA',
    blood_group: 'B+',
    allergies: 'None',
    enrolled_date: '2023-09-01',
    avatar_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    fee_balance: 450,
  },
  {
    id: 'std-003',
    admission_number: 'ADM-2026-003',
    first_name: 'Amara',
    last_name: 'Okafor',
    gender: 'Female' as const,
    date_of_birth: '2013-02-19',
    class_id: 'cls-102',
    class_name: 'Grade 9 - Beta',
    stream: 'Arts & Humanities',
    status: 'Active' as const,
    guardian_name: 'Dr. Samuel Okafor',
    guardian_phone: '+1 (555) 345-9876',
    guardian_email: 's.okafor@medcenter.org',
    address: '88 Heritage Way, Palo Alto, CA',
    blood_group: 'A+',
    allergies: 'Lactose Intolerant',
    enrolled_date: '2024-09-01',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    fee_balance: 1200,
  },
  {
    id: 'std-004',
    admission_number: 'ADM-2026-004',
    first_name: 'Noah',
    last_name: 'Rodriguez',
    gender: 'Male' as const,
    date_of_birth: '2012-08-27',
    class_id: 'cls-101',
    class_name: 'Grade 10 - Alpha',
    stream: 'Commerce & Economics',
    status: 'Active' as const,
    guardian_name: 'Carlos Rodriguez',
    guardian_phone: '+1 (555) 765-4321',
    guardian_email: 'crodriguez@investments.com',
    address: '22 Oceanfront Ave, Santa Monica, CA',
    blood_group: 'AB-',
    enrolled_date: '2023-09-01',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    fee_balance: 0,
  },
];

export const INITIAL_TEACHERS = [
  {
    id: 'tch-001',
    staff_id: 'STF-084',
    first_name: 'Dr. Evelyn',
    last_name: 'Hartford',
    email: 'e.hartford@edusync.edu',
    phone: '+1 (555) 901-2345',
    gender: 'Female' as const,
    department: 'Mathematics & Physics',
    qualification: 'Ph.D. Applied Mathematics (MIT)',
    specialization: 'Calculus & Quantum Mechanics',
    joining_date: '2018-08-15',
    status: 'Active' as const,
    salary: 8200,
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    subjects: ['Advanced Calculus', 'Honors Physics'],
  },
  {
    id: 'tch-002',
    staff_id: 'STF-091',
    first_name: 'Julian',
    last_name: 'Thorne',
    email: 'j.thorne@edusync.edu',
    phone: '+1 (555) 902-3456',
    gender: 'Male' as const,
    department: 'Computer Science & Robotics',
    qualification: 'M.Sc. Software Engineering (Stanford)',
    specialization: 'Artificial Intelligence & Python',
    joining_date: '2020-01-10',
    status: 'Active' as const,
    salary: 7900,
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    subjects: ['AP Computer Science A', 'Robotics Engineering'],
  },
  {
    id: 'tch-003',
    staff_id: 'STF-102',
    first_name: 'Miriam',
    last_name: 'Abbas',
    email: 'm.abbas@edusync.edu',
    phone: '+1 (555) 903-4567',
    gender: 'Female' as const,
    department: 'Modern Languages & Literature',
    qualification: 'M.A. Comparative Literature (Oxford)',
    specialization: 'World Literature & Linguistics',
    joining_date: '2019-09-01',
    status: 'Active' as const,
    salary: 7400,
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    subjects: ['English Literature', 'Creative Writing'],
  },
];
